Improve X&Y decoder to work with delimiters
Ciphey/Ciphey pull request #303
Opened 2020-08-28 14:44 UTC by lukasgabriel

Implements a fix that makes X&Y work with strings with delimiters.
Fixes #276

2020-08-28 14:47 UTC, lukasgabriel commented
I could move the ASCII table that's generated at runtime into CipheyDists before we merge, if that's something you'd recommend @brandonskerritt @Cyclic3  😄

2020-08-28 14:54 UTC, brandonskerritt commented
> I could move the ASCII table that's generated at runtime into CipheyDists before we merge, if that's something you'd recommend @brandonskerritt @Cyclic3 smile

Yes! Store it in CipheyDists. We use caching so if ASCII is accessed more than once :D

2020-08-28 16:03 UTC, brandonskerritt requested changes

2020-08-28 16:03 UTC, brandonskerritt commented on ciphey/basemods/Crackers/XandY.py
> +            logger.trace("X-Y Cracker ecountered UnicodeDecodeError when trying to crack ctext.")
Make this into one trace, use string formatting :)

2020-08-28 16:03 UTC, brandonskerritt commented on ciphey/basemods/Crackers/XandY.py
> -        if len(cset) != 2:
We should store the length by itself in a var, `cset_len` since we repeatedly call the function `len()`, saving us nanoseconds of time :)

2020-08-28 16:03 UTC, brandonskerritt commented on ciphey/basemods/Crackers/XandY.py
> +                val, idx = min((val, idx) for (idx, val) in enumerate(counting_list))
whats idx? can you make the variable name more clear?

2020-08-28 21:38 UTC, Cyclic3 commented
Stupid question: why can we not just use regex instead of a table?

2020-08-28 21:58 UTC, lukasgabriel commented
> Stupid question: why can we not just use regex instead of a table?

The table is used in the enCiphey part of XY to choose random characters from (that then replace the 1s and 0s in the binary).
Also, I have only very basic knowledge of RegEx and every time I try to use it, I go down a deep, deep rabbit hole.  😄 

The regular part of the XY cracker isn't affected, maybe I should have mentioned that :p

2020-08-29 00:23 UTC, brandonskerritt approved these changes

2020-08-29 10:53 UTC, merged