Add base69 decoder
Ciphey/Ciphey pull request #315
Opened 2020-08-31 05:49 UTC by lukasgabriel

As seen here: https://github.com/pshihn/base69
My code is, apart from the Ciphey-specific stuff, a 1:1 translation of the JavaScript original.
---
There is one major problem that needs to be fixed before the decoder (hopefully) works as intended:
For some reason, the output values in positions 2-7 are offset by 265.

Here's an example: 
I encode the string `AAAAAAA` with [the base69 demo.](https://pshihn.github.io/base69/)
This produces the encoded string `gALBoAUAKAFACA*A`
When I run my base69 decoder on this string, its output (in decimal form) is the following:
`[65, 321, 321, 321, 321, 321, 321]`. 
As 65 is the decimal representation of an `'A'`, the expected output would be:
 `[65, 65, 65, 65, 65, 65, 65]`.

65 + 256 = 321 - I figured out that much on myself :) This relationship holds for other input strings as well. 
For some reason, the first character out of 7 is always correct.

Being a total novice in all matters text encoding, bitwise operations and all that stuff I am at a loss here 😄 so I'll happily accept any help here. Honestly I don't really understand what the << and >> operators do at all.

When I was trying to fix it myself, I put in a few print statements so it's easier to trace the steps the decoder takes and where it trips up (and learn about the bitwise operators in the process).

2020-08-31 07:51 UTC, SkeletalDemise commented
Nice. I was also trying to implement a Base69 decoder. I think I got stuck with the same bug as you did. Things weren't working right even though I did a close to 1:1 Python implementation of the JavaScript so I kinda gave up. 
Also, here's some information about bitwise operators that might be useful:
https://wiki.python.org/moin/BitwiseOperators
https://www.w3schools.com/js/js_bitwise.asp

2020-08-31 08:14 UTC, lukasgabriel commented
@SkeletalDemise thanks a lot! I'm sure we can find a solution if we look into it more. We can always just ask the dev of the original for advice.

2020-08-31 11:13 UTC, brandonskerritt requested changes

2020-08-31 11:13 UTC, brandonskerritt commented on ciphey/basemods/Decoders/base69.py
> +# community
You are no longer community so don't include this + your github repo :) 

This was purely so we could track down who wrote the original code easily && for our tag system that's coming soon:tm:

2020-08-31 11:13 UTC, brandonskerritt commented on ciphey/basemods/Decoders/base69.py
> +        for i in range(7):
this looks hard O.O

2020-09-01 11:26 UTC, Cyclic3 commented
The code you are translating from uses a byte array, so all operations happen mod 256. You can easily (and hackily!) replicate this behaviour by just running `x % 256` on each output byte `x` when you've decoded it.

2020-09-02 13:08 UTC, Cyclic3 commented
The README for base69 says that you can work out how many null bytes were added using the penultimate character. This would mean that we could decode data such as 0x01000100  without losing the terminal null byte

2020-09-02 13:10 UTC, lukasgabriel commented
> 
> 
> The README for base69 says that you can work out how many null bytes were added using the penultimate character. This would mean that we could decode data such as 0x01000100 without losing the terminal null byte

@Cyclic3 can you tell me what I'd need to change to make that work? 😄

2020-09-02 13:20 UTC, Cyclic3 commented
I think you just need to read the n-1'th character, parse it as an integer, and trim that many bytes off it

2020-09-06 00:32 UTC, lukasgabriel commented
Finally working & thoroughly tested. Should work without issues with the vast majority of inputs. Collision with other decoders (namely reverse) will be solved when the new checker arrives.

2020-09-06 00:47 UTC, bee-san approved these changes

2020-09-06 00:47 UTC, merged