ROT47 decoder
Ciphey/Ciphey pull request #435
Opened 2020-09-29 08:34 UTC by aldogutierrez

Finished ROT47 decoder.

---------------------
I made the mistake to commit and push without making a new branch, so I reverted those changes and pushed them to a new branch, I apologize for any inconvenience

2020-09-29 21:23 UTC, bee-san commented
Hey, unfortunately ROT47 is a cracker, not a decoder so we can only accept submissions in the form of C++ code. We already have a ROT26 cracker, so to make it ROT47 I am under the assumption that we only need to change the alphabet out.

2020-09-29 22:50 UTC, Cyclic3 commented
No it's not, this is a decoder

2020-09-29 22:50 UTC, Cyclic3 commented
honestly

2020-10-01 11:00 UTC, bee-san commented
Hey, please fix this:

```
       for character in encrypted_words:
>           decoded_words += decoder_dict.get(character)
E           TypeError: can only concatenate str (not "NoneType") to str
```

You can test it is fixed by running `pytest` on your machine :)

2020-10-01 12:26 UTC, bee-san requested changes

2020-10-01 12:26 UTC, bee-san commented on ciphey/basemods/Decoders/rot47.py
> +        for character in encrypted_words:
this is what is breaking :)

2020-10-01 12:26 UTC, bee-san commented on ciphey/basemods/Decoders/rot47.py
> +        encode_alphabet = '!\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ '
This should go into CipheyDists, see the wiki for help :)

2020-10-01 12:26 UTC, bee-san commented on ciphey/basemods/Decoders/rot47.py
> +        decoder_alphabet = 'PQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~!\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNO '
This should go into CipheyDists, see the wiki for help :)

2020-10-01 12:26 UTC, bee-san commented on ciphey/basemods/Decoders/rot47.py
> +        decoder_dict = dict(zip(encode_alphabet, decoder_alphabet))
This should go into CipheyDists, see the wiki for help :)

2020-10-01 12:26 UTC, bee-san commented on ciphey/basemods/Decoders/rot47.py
> +        return 0.5
Priority should be way lower, try 0.05 :)

2020-10-03 17:40 UTC, SkeletalDemise commented
I'm closing this because ROT47 will actually need to be a C++ cracker. ROT47 uses an alphabet of ASCII characters 33 to 126, making an alphabet length of 94. Only adding ROT47 would be like only adding ROT13 without adding ROT 1-25. 

We'll need a cracker that can decode ROT 1-94 using the ROT47 alphabet. It should be easy to just use the existing caesar cracker with the ROT47 alphabet.

2020-10-03 17:40 UTC, closed without merging