Feature/ook decoder
Ciphey/Ciphey pull request #484
Opened 2020-10-06 11:24 UTC by Ozzyz

## Add Ook decoder
The most requested feature ever! Now that Ciphey finally has a brainfuck decoder, it is time to introduce Ook! 
Ook is identical to brainfuck, except that each character in brainfuck is replaced by Orangutang words.
For instance, `>` in brainfuck is `Ook. Ook?` in Ook.

You can read more about Ook [here](https://esolangs.org/wiki/Ook!)

## Remains to be done:
- [ ] Add Ook translation to CipheyDists

2020-10-06 12:01 UTC, bee-san approved these changes

2020-10-10 09:00 UTC, SkeletalDemise requested changes

2021-05-20 10:28 UTC, bee-san commented
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

2021-05-20 10:32 UTC, Ozzyz commented
@bee-san - I approve :)

2025-03-04 21:02 UTC, closed without merging