Update README.md
Ciphey/Ciphey pull request #505
Opened 2020-10-17 13:28 UTC by bee-san

We're no longer 30+ things, we're now 50+ things (in 1 new decoder or whatever) :smile:

2020-10-22 12:31 UTC, Cyclic3 requested changes
May I suggest "methods" or "systems" instead of "encryptions"?

2020-10-23 06:41 UTC, SkeletalDemise approved these changes

2020-10-23 06:48 UTC, SkeletalDemise commented
I'm merging this because I think it's more clear now. I changed the wording of it to include encodings too and added some more examples. In my opinion, "methods" or "systems" are both too vague. Also, classical ciphers like the Vigenere cipher or the Affine cipher are encryptions and it's not incorrect to call them that.

2020-10-23 11:16 UTC, Cyclic3 approved these changes

2020-10-23 11:23 UTC, merged